Traceback (most recent call last):
  File "/home/donald/PycharmProjects/SuperSploit-V1.0.5/source/core/help.py", line 37, in help
    cmd = subprocess.Popen(a.split(" "), stdout=PIPE, stdin=PIPE, stderr=PIPE)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1901, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: ''
Traceback (most recent call last):
  File "/home/donald/PycharmProjects/SuperSploit-V1.0.5/source/core/help.py", line 37, in help
    cmd = subprocess.Popen(a.split(" "), stdout=PIPE, stdin=PIPE, stderr=PIPE)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1901, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: ''
Traceback (most recent call last):
  File "/home/donald/PycharmProjects/SuperSploit-V1.0.5/source/core/help.py", line 37, in help
    cmd = subprocess.Popen(a.split(" "), stdout=PIPE, stdin=PIPE, stderr=PIPE)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1901, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '"'
Traceback (most recent call last):
  File "/home/donald/PycharmProjects/SuperSploit-V1.0.5/source/core/inputHandler.py", line 65, in check
    functions[inputs.index(data.split(" ")[0])](data)
  File "/home/donald/PycharmProjects/SuperSploit-V1.0.5/source/core/use.py", line 9, in __init__
    data[2] = int(data[2])
                  ~~~~^^^
IndexError: list index out of range
